### ISSUE TITLE
Quarantine message has incorrect pluralisation

### ISSUE THREAD

**Issue by niax** [VibroAxe/discoball-moderator#1]
When quarantining someone for 1 minute, the message in the quarantine channel reads:

> BADPERSON you have been quarantined by GOD for 1 minutes for bad behaviour

It should read:

> BADPERSON you have been quarantined by GOD for 1 minute for bad behaviour

**Comment by VibroAxe** [comment]
Only fixed in the #quarantine message, not the inchannel message
